// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: proto/menu.proto

package menuv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_proto_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{0}
}

func (x *MenuItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MenuItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MenuItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuItemRequest) Reset() {
	*x = CreateMenuItemRequest{}
	mi := &file_proto_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuItemRequest) ProtoMessage() {}

func (x *CreateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMenuItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMenuItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMenuItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateMenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItem      *MenuItem              `protobuf:"bytes,1,opt,name=menu_item,json=menuItem,proto3" json:"menu_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuItemResponse) Reset() {
	*x = CreateMenuItemResponse{}
	mi := &file_proto_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuItemResponse) ProtoMessage() {}

func (x *CreateMenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuItemResponse.ProtoReflect.Descriptor instead.
func (*CreateMenuItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMenuItemResponse) GetMenuItem() *MenuItem {
	if x != nil {
		return x.MenuItem
	}
	return nil
}

type GetMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemRequest) Reset() {
	*x = GetMenuItemRequest{}
	mi := &file_proto_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemRequest) ProtoMessage() {}

func (x *GetMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemRequest.ProtoReflect.Descriptor instead.
func (*GetMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{3}
}

func (x *GetMenuItemRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItem      *MenuItem              `protobuf:"bytes,1,opt,name=menu_item,json=menuItem,proto3" json:"menu_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemResponse) Reset() {
	*x = GetMenuItemResponse{}
	mi := &file_proto_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemResponse) ProtoMessage() {}

func (x *GetMenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemResponse.ProtoReflect.Descriptor instead.
func (*GetMenuItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{4}
}

func (x *GetMenuItemResponse) GetMenuItem() *MenuItem {
	if x != nil {
		return x.MenuItem
	}
	return nil
}

type GetMenuItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemsRequest) Reset() {
	*x = GetMenuItemsRequest{}
	mi := &file_proto_menu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemsRequest) ProtoMessage() {}

func (x *GetMenuItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemsRequest.ProtoReflect.Descriptor instead.
func (*GetMenuItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{5}
}

type GetMenuItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItems     []*MenuItem            `protobuf:"bytes,1,rep,name=menu_items,json=menuItems,proto3" json:"menu_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemsResponse) Reset() {
	*x = GetMenuItemsResponse{}
	mi := &file_proto_menu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemsResponse) ProtoMessage() {}

func (x *GetMenuItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemsResponse.ProtoReflect.Descriptor instead.
func (*GetMenuItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{6}
}

func (x *GetMenuItemsResponse) GetMenuItems() []*MenuItem {
	if x != nil {
		return x.MenuItems
	}
	return nil
}

type UpdateMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuItemRequest) Reset() {
	*x = UpdateMenuItemRequest{}
	mi := &file_proto_menu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemRequest) ProtoMessage() {}

func (x *UpdateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMenuItemRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMenuItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateMenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItem      *MenuItem              `protobuf:"bytes,1,opt,name=menu_item,json=menuItem,proto3" json:"menu_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuItemResponse) Reset() {
	*x = UpdateMenuItemResponse{}
	mi := &file_proto_menu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemResponse) ProtoMessage() {}

func (x *UpdateMenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMenuItemResponse) GetMenuItem() *MenuItem {
	if x != nil {
		return x.MenuItem
	}
	return nil
}

type DeleteMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuItemRequest) Reset() {
	*x = DeleteMenuItemRequest{}
	mi := &file_proto_menu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuItemRequest) ProtoMessage() {}

func (x *DeleteMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMenuItemRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuItemResponse) Reset() {
	*x = DeleteMenuItemResponse{}
	mi := &file_proto_menu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuItemResponse) ProtoMessage() {}

func (x *DeleteMenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteMenuItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMenuItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_menu_proto protoreflect.FileDescriptor

const file_proto_menu_proto_rawDesc = "" +
	"\n" +
	"\x10proto/menu.proto\x12\amenu.v1\"\xa4\x01\n" +
	"\bMenuItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"c\n" +
	"\x15CreateMenuItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"H\n" +
	"\x16CreateMenuItemResponse\x12.\n" +
	"\tmenu_item\x18\x01 \x01(\v2\x11.menu.v1.MenuItemR\bmenuItem\"$\n" +
	"\x12GetMenuItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"E\n" +
	"\x13GetMenuItemResponse\x12.\n" +
	"\tmenu_item\x18\x01 \x01(\v2\x11.menu.v1.MenuItemR\bmenuItem\"\x15\n" +
	"\x13GetMenuItemsRequest\"H\n" +
	"\x14GetMenuItemsResponse\x120\n" +
	"\n" +
	"menu_items\x18\x01 \x03(\v2\x11.menu.v1.MenuItemR\tmenuItems\"s\n" +
	"\x15UpdateMenuItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"H\n" +
	"\x16UpdateMenuItemResponse\x12.\n" +
	"\tmenu_item\x18\x01 \x01(\v2\x11.menu.v1.MenuItemR\bmenuItem\"'\n" +
	"\x15DeleteMenuItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"2\n" +
	"\x16DeleteMenuItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x9d\x03\n" +
	"\vMenuService\x12Q\n" +
	"\x0eCreateMenuItem\x12\x1e.menu.v1.CreateMenuItemRequest\x1a\x1f.menu.v1.CreateMenuItemResponse\x12H\n" +
	"\vGetMenuItem\x12\x1b.menu.v1.GetMenuItemRequest\x1a\x1c.menu.v1.GetMenuItemResponse\x12K\n" +
	"\fGetMenuItems\x12\x1c.menu.v1.GetMenuItemsRequest\x1a\x1d.menu.v1.GetMenuItemsResponse\x12Q\n" +
	"\x0eUpdateMenuItem\x12\x1e.menu.v1.UpdateMenuItemRequest\x1a\x1f.menu.v1.UpdateMenuItemResponse\x12Q\n" +
	"\x0eDeleteMenuItem\x12\x1e.menu.v1.DeleteMenuItemRequest\x1a\x1f.menu.v1.DeleteMenuItemResponseB\x1bZ\x19menu-service/proto/menuv1b\x06proto3"

var (
	file_proto_menu_proto_rawDescOnce sync.Once
	file_proto_menu_proto_rawDescData []byte
)

func file_proto_menu_proto_rawDescGZIP() []byte {
	file_proto_menu_proto_rawDescOnce.Do(func() {
		file_proto_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_menu_proto_rawDesc), len(file_proto_menu_proto_rawDesc)))
	})
	return file_proto_menu_proto_rawDescData
}

var file_proto_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_menu_proto_goTypes = []any{
	(*MenuItem)(nil),               // 0: menu.v1.MenuItem
	(*CreateMenuItemRequest)(nil),  // 1: menu.v1.CreateMenuItemRequest
	(*CreateMenuItemResponse)(nil), // 2: menu.v1.CreateMenuItemResponse
	(*GetMenuItemRequest)(nil),     // 3: menu.v1.GetMenuItemRequest
	(*GetMenuItemResponse)(nil),    // 4: menu.v1.GetMenuItemResponse
	(*GetMenuItemsRequest)(nil),    // 5: menu.v1.GetMenuItemsRequest
	(*GetMenuItemsResponse)(nil),   // 6: menu.v1.GetMenuItemsResponse
	(*UpdateMenuItemRequest)(nil),  // 7: menu.v1.UpdateMenuItemRequest
	(*UpdateMenuItemResponse)(nil), // 8: menu.v1.UpdateMenuItemResponse
	(*DeleteMenuItemRequest)(nil),  // 9: menu.v1.DeleteMenuItemRequest
	(*DeleteMenuItemResponse)(nil), // 10: menu.v1.DeleteMenuItemResponse
}
var file_proto_menu_proto_depIdxs = []int32{
	0,  // 0: menu.v1.CreateMenuItemResponse.menu_item:type_name -> menu.v1.MenuItem
	0,  // 1: menu.v1.GetMenuItemResponse.menu_item:type_name -> menu.v1.MenuItem
	0,  // 2: menu.v1.GetMenuItemsResponse.menu_items:type_name -> menu.v1.MenuItem
	0,  // 3: menu.v1.UpdateMenuItemResponse.menu_item:type_name -> menu.v1.MenuItem
	1,  // 4: menu.v1.MenuService.CreateMenuItem:input_type -> menu.v1.CreateMenuItemRequest
	3,  // 5: menu.v1.MenuService.GetMenuItem:input_type -> menu.v1.GetMenuItemRequest
	5,  // 6: menu.v1.MenuService.GetMenuItems:input_type -> menu.v1.GetMenuItemsRequest
	7,  // 7: menu.v1.MenuService.UpdateMenuItem:input_type -> menu.v1.UpdateMenuItemRequest
	9,  // 8: menu.v1.MenuService.DeleteMenuItem:input_type -> menu.v1.DeleteMenuItemRequest
	2,  // 9: menu.v1.MenuService.CreateMenuItem:output_type -> menu.v1.CreateMenuItemResponse
	4,  // 10: menu.v1.MenuService.GetMenuItem:output_type -> menu.v1.GetMenuItemResponse
	6,  // 11: menu.v1.MenuService.GetMenuItems:output_type -> menu.v1.GetMenuItemsResponse
	8,  // 12: menu.v1.MenuService.UpdateMenuItem:output_type -> menu.v1.UpdateMenuItemResponse
	10, // 13: menu.v1.MenuService.DeleteMenuItem:output_type -> menu.v1.DeleteMenuItemResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_menu_proto_init() }
func file_proto_menu_proto_init() {
	if File_proto_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_menu_proto_rawDesc), len(file_proto_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_menu_proto_goTypes,
		DependencyIndexes: file_proto_menu_proto_depIdxs,
		MessageInfos:      file_proto_menu_proto_msgTypes,
	}.Build()
	File_proto_menu_proto = out.File
	file_proto_menu_proto_goTypes = nil
	file_proto_menu_proto_depIdxs = nil
}
